---
title: "Package contribution primer"
author: "Lim Yun Ching"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
## Workflow for contributing to this package

1. Pull code from repo
2. Create a new branch with the feature you are developing (using git branch) and switch to it
3. Update tests with the results you expect when your new functionality is built (in tests/testthat folder)
4. Update R code (in R folder), make sure you also include Roxygen comments
5. Install devtools by running `install.packages("devtools")` (only once needed)
6. Run devtools::document() to update R documentation from your Roxygen comments
7. Install Rtools by downloading it from https://cran.r-project.org/bin/windows/Rtools/ and restart Rstudio (only once needed)
8. Test package (Build > Test package) to check that your new functionality meets your expectations and historical tests. 
9. Check package is building properly (Build > Check Package)
10. Update the version number in DESCRIPTION file (see Version Numbers section below) if necessary.
11. Submit a pull request which will check package on CI server

## Version Numbers

This package uses [semantic versioning](https://semver.org/). In essence, the package's version is of the form MAJOR.MINOR.PATCH and increments using the below logic:

* MAJOR version when you make incompatible API changes,
* MINOR version when you add functionality in a backwards-compatible manner, and
* PATCH version when you make backwards-compatible bug fixes.
