---
title: "EZ econs chart pack"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
source("C:\\Users\\ylim\\Documents\\R projects\\tidymas\\R\\convenience.R")
```

#UK

## GDP
```{r uk_gdp}
uk_ngdp_yoy <- getMB("gbnaac00412") %>% q_yoy() %>% ggXTS(title = "UK Nominal GDP YoY") + hline(0)
uk_rgdp_yoy <- getMB("gbnaac00512") %>% q_yoy() %>% ggXTS(title = "UK Real GDP YoY") + hline(0)
grid.arrange(uk_ngdp_yoy, uk_rgdp_yoy, nrow = 2)

```

## Inflation
```{r uk_inf}
uk_cpi_yoy <- getMB("gbpric00011") %>% m_yoy %>% ggXTS("UK CPI YoY") + hline(2)
uk_cpi_mom <- getMB("gbpric00011") %>% m_mom %>% ggXTS("UK CPI MoM") 
grid.arrange(uk_cpi_yoy, uk_cpi_mom, nrow = 2)
```

## UK PMIs
```{r uk_lead}
uk_comp_pmi <- getMB("markit_pmigbcomob")["2008/9999"] %>% 
  ggXTS(title = "UK Composite PMI") + hline(50)
uk_manu_pmi <- getMB("markit_pmigbmanpm")["2008/9999"] %>% 
  ggXTS(title = "UK Manufacturing PMI") + hline(50)
uk_cons_pmi <- getMB("markit_pmigbconob")["2008/9999"] %>% 
  ggXTS(title = "UK Construction PMI") + hline(50) 
uk_svcs_pmi <- getMB("markit_pmigbserob")["2008/9999"] %>% 
  ggXTS(title = "UK Services PMI") + hline(50)
grid.arrange(uk_comp_pmi, uk_manu_pmi, uk_cons_pmi, uk_svcs_pmi, ncol = 2)
```

## Consumption
```{r uk_consumption}
uk_gfk <- getMB("gbsurv0515")["2008/9999"] %>% ggXTS(title = "GfK Consumer Survey")
uk_nw_yoy <- getMB("gbcons0207")["2008/9999"] %>% m_yoy() %>% ggXTS(title = "Nationwide Price Index")
grid.arrange(uk_gfk, uk_nw_yoy, nrow = 2)

```

## Investments

## Govt

## Exports

## Imports

# Eurozone

## Headlines
```{r ez_headlines}
ez_core_inf_yoy <- getMB("eupric0151") %>% m_yoy() %>% ggXTS(title = "EZ Core Inflation")
ez_unemp <- getMB("eulama3600") %>% ggXTS(title = "EZ Unemployment Rate")
grid.arrange(ez_core_inf_yoy, ez_unemp)
```

## EZ PMIs
```{r ez_pmis}
ez_comp_pmi <- getMB("markit_pmiezcomob")["2008/9999"] %>% 
  ggXTS(title = "EZ Composite PMI") + hline(50)
ez_manu_pmi <- getMB("markit_pmiezmanpm")["2008/9999"] %>% 
  ggXTS(title = "EZ Manufacturing PMI") + hline(50)
ez_cons_pmi <- getMB("markit_pmiezconob")["2008/9999"] %>% 
  ggXTS(title = "EZ Construction PMI") + hline(50)
ez_svcs_pmi <- getMB("markit_pmiezserob")["2008/9999"] %>% 
  ggXTS(title = "EZ Services PMI") + hline(50)
grid.arrange(ez_comp_pmi, ez_manu_pmi, ez_cons_pmi, ez_svcs_pmi, ncol = 2)
```

# Germany

## German PMI
```{r de_pmi}
de_comp_pmi <- getMB("markit_pmidecomob")["2008/9999"] %>% 
  ggXTS(title = "Germany Composite PMI") + hline(50)
de_manu_pmi <- getMB("markit_pmidemanpm")["2008/9999"] %>% 
  ggXTS(title = "Germany Manufacturing PMI") + hline(50)
de_cons_pmi <- getMB("markit_pmideconob")["2008/9999"] %>% 
  ggXTS(title = "Germany Construction PMI") + hline(50)
de_svcs_pmi <- getMB("markit_pmideserob")["2008/9999"] %>% 
  ggXTS(title = "Germany Services PMI") + hline(50)
grid.arrange(de_comp_pmi, de_manu_pmi, de_cons_pmi, de_svcs_pmi, ncol = 2)
```

# France

## France PMI
```{r fr_pmi}
fr_comp_pmi <- getMB("markit_pmifrcomob")["2008/9999"] %>% 
  ggXTS(title = "France Composite PMI") + hline(50)
fr_manu_pmi <- getMB("markit_pmifrmanpm")["2008/9999"] %>% 
  ggXTS(title = "France Manufacturing PMI") + hline(50)
fr_cons_pmi <- getMB("markit_pmifrconob")["2008/9999"] %>% 
  ggXTS(title = "France Construction PMI") + hline(50)
fr_svcs_pmi <- getMB("markit_pmifrserob")["2008/9999"] %>% 
  ggXTS(title = "France Services PMI") + hline(50)
grid.arrange(fr_comp_pmi, fr_manu_pmi, fr_cons_pmi, fr_svcs_pmi, ncol = 2)
```

# Italy

## Italy PMI
```{r it_pmi}
it_comp_pmi <- getMB("markit_pmiitcomob")["2008/9999"] %>% 
  ggXTS(title = "Italy Composite PMI") + hline(50)
it_manu_pmi <- getMB("markit_pmiitmanpm")["2008/9999"] %>% 
  ggXTS(title = "Italy Manufacturing PMI") + hline(50)
it_cons_pmi <- getMB("markit_pmiitconob")["2008/9999"] %>% 
  ggXTS(title = "Italy Construction PMI") + hline(50)
it_svcs_pmi <- getMB("markit_pmiitserob")["2008/9999"] %>% 
  ggXTS(title = "Italy Services PMI") + hline(50)
grid.arrange(it_comp_pmi, it_manu_pmi, it_cons_pmi, it_svcs_pmi, ncol = 2)
```

# Spain

## Spain PMI
```{r es_pmi}
es_comp_pmi <- getMB("markit_pmiescomob")["2008/9999"] %>% 
  ggXTS(title = "Spain Composite PMI") + hline(50)
es_manu_pmi <- getMB("markit_pmiesmanpm")["2008/9999"] %>% 
  ggXTS(title = "Spain Manufacturing PMI") + hline(50)
es_cons_pmi <- blank_chart() #Spain has no construction PMI
es_svcs_pmi <- getMB("markit_pmiesserob")["2008/9999"] %>% 
  ggXTS(title = "Spain Services PMI") + hline(50)
grid.arrange(es_comp_pmi, es_manu_pmi, es_cons_pmi, es_svcs_pmi, ncol = 2)
```
# Ireland

## Ireland PMI
```{r ie_pmi}
ie_comp_pmi <- getMB("markit_pmiiecomob")["2008/9999"] %>% 
  ggXTS(title = "Ireland Composite PMI") + hline(50)
ie_manu_pmi <- getMB("markit_pmiiemanpm")["2008/9999"] %>% 
  ggXTS(title = "Ireland Manufacturing PMI") + hline(50)
ie_cons_pmi <- getMB("markit_pmiieconob")["2008/9999"] %>% 
  ggXTS(title = "Ireland Construction PMI") + hline(50)
ie_svcs_pmi <- getMB("markit_pmiieserob")["2008/9999"] %>% 
  ggXTS(title = "Ireland Services PMI") + hline(50)
grid.arrange(ie_comp_pmi, ie_manu_pmi, ie_cons_pmi, ie_svcs_pmi, ncol = 2)
```
